# Generated by Django 4.1.4 on 2023-01-26 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sell', '0002_owner_announcement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='announcement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
